export const $Z = Symbol('orb-core')
export const $L = Symbol('list-core')
export const MODEL_SELF = Symbol('m-self')
export const SYMBOL_ISMODEL = Symbol('orbz-ismodel')
export const Z_DEFS = Symbol('model-def')
export const Z_MODEL_IDS = Symbol('model-id')
export const MODEL_IMPLEMENTS = Symbol('model-id')