export const $Z = Symbol.for('orbz-orb-core')
export const $L = Symbol.for('orbz-list-core')
export const MODEL_SELF = Symbol.for('orbz-m-self')
export const SYMBOL_ISMODEL = Symbol.for('orbz-orbz-ismodel')
export const Z_DEFS = Symbol.for('orbz-model-def')
export const Z_MODEL_IDS = Symbol.for('orbz-model-id')
export const MODEL_IMPLEMENTS = Symbol.for('orbz-model-implements')